from enum import Enum


class EventType(str, Enum):
    MESSAGE_CREATED = "message.created"
    MESSAGE_STREAMING = "message.streaming"
    MESSAGE_COMPLETED = "message.completed"
    ORCHESTRATOR_TASK_STARTED = "orchestrator.task.started"
    ORCHESTRATOR_TASK_COMPLETED = "orchestrator.task.completed"
    AGENT_CALL_STARTED = "agent.call.started"
    AGENT_CALL_COMPLETED = "agent.call.completed"
    AGENT_PROCESS_STARTED = "agent.process.started"
    AGENT_PROCESS_COMPLETED = "agent.process.completed"
    AGENT_PROCESS_TIMEOUT = "agent.process.timeout"
    PROJECT_CREATED = "project.created"
    WORKSPACE_FILE_CHANGED = "workspace.file_changed"
    WORKSPACE_CREATED = "workspace.created"
    WORKSPACE_SNAPSHOT_CREATED = "workspace.snapshot.created"
    WORKSPACE_RESTORE_COMPLETED = "workspace.restore.completed"
    WORKSPACE_IMPORT_COMPLETED = "workspace.import.completed"
    WORKSPACE_DIFF_READY = "workspace.diff_ready"
    TEAM_MEMBER_ADDED = "team.member.added"
    AUDIT_RECORDED = "audit.recorded"
    PREVIEW_READY = "preview.ready"
    PREVIEW_CREATED = "preview.created"
    BUILD_QUEUED = "build.queued"
    BUILD_STARTED = "build.started"
    BUILD_LOG = "build.log"
    BUILD_COMPLETED = "build.completed"
    BUILD_FAILED = "build.failed"
    CONTEXT_PACK_CREATED = "context_pack.created"
    ORCHESTRATOR_PLAN_PAUSED = "orchestrator.plan.paused"
    ORCHESTRATOR_PLAN_RESUMED = "orchestrator.plan.resumed"
    ARTIFACT_DETECTED = "artifact.detected"
    ARTIFACT_CREATED = "artifact.created"
    ARTIFACT_UPDATED = "artifact.updated"
    ARTIFACT_DETECTION_FAILED = "artifact.detection_failed"
